### ISSUE TITLE
Add a cli tool to generate a sharex config

### ISSUE THREAD

**Issue by hannesfant** [hannesfant/sharex-uploader#4]
Create a js file in a folder called `utils` in the root of the project dir which generates a sharex config file like the one in the readme. The tool accepts one argument, the URL to the installation, and then generates a valid sharex config based on that and the key in the config.json file.

**Comment by MuriloucoLouco** [comment]
Hi, I can do this one. I just didn't get what exactly am i suposed to do. It will create a new sharex config using the key on the sharex config that i already have on the root folder, and a URL to installation. What is the URL to installation?
EDIT: I think i understood, the cli tool will create a custom uploader setting, and the URL to installation is the RequestURL. Is that right?

**Comment by hannesfant** [comment]
The url is the argument for the cli tool, so for my installation at https://i.hannesf.net would be https://i.hannesf.net - without the /upload. The tool would add the upload itself.
